### ISSUE TITLE
Tilesets not loading tiles

### ISSUE THREAD

**Issue by timschwartz** [fallahn/tmxlite#107]
I'm trying to parse a map using tmxlite, and I'm having trouble with tilesets. This is my code:

```
const auto &tilesets = map.getTilesets();
for(const auto &tileset : tilesets)
{
    this->TilesetDump(tileset);
}


void Parser::TilesetDump(const tmx::Tileset tileset)
{
    std::vector<tmx::Tileset::Tile> tiles = tileset.getTiles();

    std::cout << "    Tileset: " << tileset.getName() << std::endl;
    std::cout << "        Tile count: " << (unsigned)tileset.getTileCount() << std::endl;
    std::cout << "        Tile count 2: " << (unsigned)tiles.size() << std::endl;
    std::cout << "        Image path: " << tileset.getImagePath() << std::endl;
    std::cout << "        First GID: " << (unsigned)tileset.getFirstGID() << std::endl;
    std::cout << "        Last GID: " << (unsigned)tileset.getLastGID() << std::endl;
}
```

This is the output:

```
    Tileset: greendale_interior
        Tile count: 0
        Tile count 2: 0
        Image path: /home/tim/projects/hawkthorne-journey/src/images/tilesets/greendale-interior.png
        First GID: 1
test-program: /home/tim/the-seed/projects/tmxlite/tmxlite/src/Tileset.cpp:229: uint32_t tmx::Tileset::getLastGID() const: Assertion `!m_tiles.empty()' failed.
Aborted
```

The image path *is* correct but for some reason I can't access the tiles. Is there something I need to do manually to load the image?

**Comment by fallahn** [comment]
`The image path is correct but for some reason I can't access the tiles. Is there something I need to do manually to load the image?`

The parser only creates a C++ representation of the tmx map file, it doesn't do any actual asset loading. It will provide a string containing the path to the image, but you have to load this yourself as the map loader has no idea if you're using OpenGL, DirectX, SDL, Allegro etc...

As for why you have no tiles in the tile set, I couldn't say without looking at your tmx file. It might be that the specification has been updated and you're using an as yet unimplemented feature. For example tmxlite doesn't support files compressed with zstdlib as this would require adding external dependencies, so you need to use zlib instead. (If this were the case here, however, the error should be more explicit about that).

**Comment by timschwartz** [comment]
ok, i see. That file didn't include the tilecount attribute on the tileset tag. It works correctly with another tmx file that does have the tilecount attribute.

**Comment by fallahn** [comment]
Is this common in newer tileset files? If so I'd consider updating the loader to parse them

**Comment by timschwartz** [comment]
Looks like the map version number on the file that didn't work is 1.0, the one that did work is version 1.8.

**Comment by fallahn** [comment]
OK, thanks for the info!
