### ISSUE TITLE
CAN SOMEONE JUST EXPLAIN HOW TO USE THIS

### ISSUE THREAD

**Issue by LGenAgul** [fallahn/tmxlite#117]
Please someone just explain to me like you would to a 5 year old how to use this damn program because I can not set this up, I've been trying all week and couldn't find any tutorial on the internet that was not vague or confusing

**Comment by fallahn** [comment]
What's your dev environment? Windows? Linux? macOS? Which compiler / tool chain are you using, and are you using an IDE? There are a few ways to use the library, but it depends on how you are developing.

**Comment by chocolateimage** [comment]
i have the same problem, it says "undefined reference to `tmx::Map::load.....`" and how do i get the tiles, with "tileson" i can get the tiles but tileson doesnt load the map correctly (says "Missing map data...")

**Comment by chocolateimage** [comment]
i have the same problem, it says "undefined reference to `tmx::Map::load.....`" and how do i get the tiles, with "tileson" i can get the tiles but tileson doesnt load the map correctly (says "Missing map data...")

**Comment by fallahn** [comment]
'undefined reference' means that you've either not linked the library (if you've build tmxlite as a library) or not included the source files in your project. How you do that depends on your compiler and IDE/Editor.

**Comment by chocolateimage** [comment]
but how do i link the library? if i add -ltmxlite it doesn't work

**Comment by fallahn** [comment]
Do you have it installed somewhere? Did you build it from source? It shouldn't be any different from linking any other library.

**Comment by chocolateimage** [comment]
i did `sudo make install`
from here https://github.com/fallahn/tmxlite/wiki/Quick-Start

**Comment by fallahn** [comment]
Ah OK. It will have installed to /usr/lib so make sure that's in your library path when linking. The header files will be in /usr/include

**Comment by chocolateimage** [comment]
> Ah OK. It will have installed to /usr/lib so make sure that's in your library path when linking. The header files will be in /usr/include

it is not in /usr/lib

**Comment by fallahn** [comment]
Sorry, `/usr/local/lib` - you should have had something like this when you installed it: 

![Untitled-1](https://user-images.githubusercontent.com/5619252/218331844-9718c626-7f9c-4426-9da9-7880960fd13f.png)
