### ISSUE TITLE
Problem with "std::localtime" in Log.hpp line 145

### ISSUE THREAD

**Issue by Karma192** [fallahn/tmxlite#118]
I have a problem with line 145 in Log.hpp, that's create this error :
"Erreur C4996	'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. path\Log.hpp	145"
Can someone help me with that ?

**Comment by fallahn** [comment]
This is specific to MSVC - you can read about what it is and how to disable it here: https://learn.microsoft.com/en-us/cpp/c-runtime-library/security-features-in-the-crt?view=msvc-170 and here: https://stackoverflow.com/a/20753468/6740859
