### ISSUE TITLE
A little help?

### ISSUE THREAD

**Issue by SuckyNoob** [fallahn/tmxlite#12]
I really can't figure out how to get this into my project. Same for the original SFML Tmx Loader....

I include the include folder. That doesn't work. There are no .libs. 

None of it works. Can you point me to a tutorial or something that shows me how to get these into my project? I'm using VS 2017 and SFML 2.4+

As for the original tmxloader for SFML I try and use cmake with it. It will give me static libs, only the pugi.dlls and no tmxloader .dll.

I've tried manually including them straight into my solution as their hpps and cpps. For both versions of the loader, and none of it works.

This time i included the src directory in the includes instead of just the "include" directory.

Now get this error

`On line #106 of Log.Hpp (Using VS 2017 64 bit)

std::string outstring

argument of type "const char *" is incompatible with paramaeter of type "LPCWSTR"`

**Comment by fallahn** [comment]
Sounds like you're most of the way there. If you want to build the libraries you should be able to open the tmxlite solution in vs and hit build (once for both release and debug versions). If including the source works for you then that's fine too, commenting out line 106 won't do you any harm.

**Comment by SuckyNoob** [comment]
Hey. Thanks for the reply. I am a noob as my name says haha. So I got the sfml-tmxloader-next branch to work. using CMAKE

But only up to the point that when I go to build the solution in Visual Studio 2017. When I do that the only error that pops out is that.

\Debug pugi-d.lib and pugi.lib cannot be found. CMAKE never generates them.  And I can't seem to generate them by building the solution. Just the pugi.dll's. The only things that get generated are the pugi-d and pugi .ilk and .pdb files.

Am I missing something?

**Comment by SuckyNoob** [comment]
Ah okay so I figured it out now with a little help from a friend.

Tmxlite I didn't figure out but for the SFML-tmxloader-next what I had to do after using cmake was go into the "pugi" project inside pugiconfig.hpp and UNcomment line #30. Then build pugi project. Then go and rebuild the tmxloader project and the solution.

Can't wait to try it out!
