### ISSUE TITLE
meson.build version doesn't match git tags

### ISSUE THREAD

**Issue by pedro-w** [fallahn/tmxlite#122]
In `meson.build` it's still 1.2.1 but the recently-released version is tagged as 1.4.1 with git. It all seems to work fine but it's a bit confusing.

https://github.com/fallahn/tmxlite/blob/2755e96fea12927342fd14ba3724124f5ecf8fce/meson.build#L1-L10

**Comment by fallahn** [comment]
Oops! I'll fix that, thanks 😁
