### ISSUE TITLE
Question: getLastGID() function feature

### ISSUE THREAD

**Issue by Howld** [fallahn/tmxlite#13]
Link: https://github.com/fallahn/tmxlite/blob/master/tmxlite/include/tmxlite/Tileset.hpp#L116

The function feature says "Returns the last GID of this tile set. This is the ID of the last tile in the tile set.".
I think if 1 to 1024, it will be return 1024, but it returns 1025. Did I missed something?

**Comment by fallahn** [comment]
Ah, yes this might be a bug. I'll have to check if I've used this somewhere in the renderering examples to do something weird, but I think you're right. Good catch!
