### ISSUE TITLE
Unable to start program. libtmxlite-s-d.lib is not a valid win32 application

### ISSUE THREAD

**Issue by DFelipehDEV** [fallahn/tmxlite#134]
Hello! Im trying to run the SFML example but its showing that Win32 is not a valid win32 application.
![imagem](https://github.com/fallahn/tmxlite/assets/56834989/e887852f-bba1-4853-a455-1649ad4ca516)

**Comment by Agenteec** [comment]
You must go to the directory "C:\Users\****\Downloads\ltmxlite-master\x64\Debug" where your exe file will be compiled

**Comment by DFelipehDEV** [comment]
> You must go to the directory "C:\Users---\Downloads\ltmxlite-master\x64\Debug" where your exe file will be compiled

I have gone there but only the libs are there
![imagem](https://github.com/fallahn/tmxlite/assets/56834989/2df0b99b-4b88-43f7-afc6-3087bfcc458e)

**Comment by fallahn** [comment]
Right click on the SFMLExample project, go to properties and [set up the include and link paths](https://www.sfml-dev.org/tutorials/2.6/start-vc.php#creating-and-configuring-a-sfml-project) to your SFML install.

Right click on the SFMLExample project and select `Set as Startup Project`

![startup](https://github.com/fallahn/tmxlite/assets/5619252/5fd4ab53-bce9-4885-ab76-928fc8ba8b07)

Go to build configuration

![config_manager](https://github.com/fallahn/tmxlite/assets/5619252/e31f2ad0-f0ee-448a-8f7a-b2dc7aa982d0)

and in the configuration manager make sure it's selected for building

![config_manager_2](https://github.com/fallahn/tmxlite/assets/5619252/8af46b50-4565-494f-af40-55cde8aca282)

**Comment by DFelipehDEV** [comment]
> Right click on the SFMLExample project, go to properties and [set up the include and link paths](https://www.sfml-dev.org/tutorials/2.6/start-vc.php#creating-and-configuring-a-sfml-project) to your SFML install.
> 
> Right click on the SFMLExample project and select `Set as Startup Project`
> 
> ![startup](https://user-images.githubusercontent.com/5619252/256816480-5fd4ab53-bce9-4885-ab76-928fc8ba8b07.png)
> 
> Go to build configuration
> 
> ![config_manager](https://user-images.githubusercontent.com/5619252/256816549-e31f2ad0-f0ee-448a-8f7a-b2dc7aa982d0.png)
> 
> and in the configuration manager make sure it's selected for building
> 
> ![config_manager_2](https://user-images.githubusercontent.com/5619252/256816616-8af46b50-4565-494f-af40-55cde8aca282.png)


It no longer appears the error but this appears
im sorry im new to this library type of stuff
![imagem](https://github.com/fallahn/tmxlite/assets/56834989/74652988-9799-4028-a1d5-fc0cee909300)

**Comment by fallahn** [comment]
Make sure the tmxlite path is correct in the project properties

![lib_path](https://github.com/fallahn/tmxlite/assets/5619252/0ce60150-c75d-49ce-899a-25aac8747777)

and that the library name matches (libtmxlite-s-d, or tmxlite.lib etc) with the version of tmxlite that you built

![lib_name](https://github.com/fallahn/tmxlite/assets/5619252/bcc4979b-d284-4b40-ad6c-e9ced9c2e7ec)

**Comment by DFelipehDEV** [comment]
Thank you that worked.
