### ISSUE TITLE
Bug: m_chunkSize in example incorrectly displays maps which are smaller than the current chunk size

### ISSUE THREAD

**Issue by Howld** [fallahn/tmxlite#14]
Link: https://github.com/fallahn/tmxlite/blob/master/SFMLExample/src/SFMLOrthogonalLayer.hpp#L95
<pre>
 sf::Vector2f m_chunkSize = sf::Vector2f(1024.f, 1024.f);
</pre>

Whether m_chunkSize means the size of map, maybe you should add a comment?

**Comment by fallahn** [comment]
A chunk is a segment of the map. The example splits the entire map into chunks of `m_chunkSize` and only draws those which are visible on screen. If the map is smaller than a single chunk then this will be the map size. I'll update the documentation in the example when I get a chance.

**Comment by Howld** [comment]
"If the map is smaller than a single chunk then this will be the map size."

Where is the code? I only find this will change m_chunkSize. 

<pre>
m_chunkSize.x = std::floor(m_chunkSize.x / tileSize.x) * tileSize.x;
</pre>
<pre>
sf::Vector2f tileCount(m_chunkSize.x / map.getTileSize().x, m_chunkSize.y / map.getTileSize().y);
</pre>

**Comment by fallahn** [comment]
Sorry, I perhaps worded that badly. If the map is smaller than the chunk size, then a single chunk is created, and the entire map is contained within it. The above code fits the chunk size to the tile size - for example the chunk size is 1024 by default. If you have a tile size of 48 it will resize to 1008 so that it fits exactly 21 tiles - because you can't have 21.3333 tiles.

**Comment by Howld** [comment]
I have a 600x600 window with a 480x480 map, and 32x32 tiles, so I think tileCount should be 15x15. Because I found code in Chunk class will add more tiles to ChunkArray, and where should be blank instead of duplicate tiles.

<pre>
for (auto y = yPos; y < yPos + tileCount.y; ++y)
 {
     for (auto x = xPos; x < xPos + tileCount.x; ++x)
</pre>

**Comment by fallahn** [comment]
Ah, OK. Well it is only an example so there are bound to be a few bugs ;)
