### ISSUE TITLE
Documentation for tmxlite

### ISSUE THREAD

**Issue by WhosMyName** [fallahn/tmxlite#17]
I appreciate your work on creating tmxlite and i'd really like to use it,
but i can't wrap my head around your code.
Maybe i'm too dumb to understand, but is there a documentation for tmxlite?
Any reference to make it easier for beginners to get into tmxlite?
Or a way to get the Logger running on linux?

**Comment by fallahn** [comment]
Hi, there're no wiki pages as such just yet (although always at the back of my mind to write them) but there is api documentation written that can be generated with [doxygen](http://www.stack.nl/~dimitri/doxygen/) using the doxy file in the documentation folder (or simply found in the comments in each of the header files). There are also  examples of the code in use for both SFML and OpenGL/SDL in the respective directories in the repository. What kind of problem do you have with the logger on linux? As far as I know it works on all supported platforms, including Android via logcat.

**Comment by fallahn** [comment]
There's now a quick start page on the wiki [here](https://github.com/fallahn/tmxlite/wiki/Quick-Start) as well as API documentation [here](https://codedocs.xyz/fallahn/tmxlite/).
