### ISSUE TITLE
Box2D intergration

### ISSUE THREAD

**Issue by louis123456** [fallahn/tmxlite#18]
Does this version also contain the box2D converter or collision detection? I can't seem to find it.

**Comment by fallahn** [comment]
No, it's not included as tmxlite is meant as a pure parser. If people would find it useful I could add it to the examples, however. For now you can probably hack apart this code which is built around a fork of tmxlite: https://github.com/fallahn/xygine/blob/master/xygine/src/tilemap/Map.cpp#L557

**Comment by louis123456** [comment]
Thank you, I think I would be using xygine altogether.
