### ISSUE TITLE
Installing?

### ISSUE THREAD

**Issue by Bramwell-Simpson** [fallahn/tmxlite#20]
I use visual studio 2017, and I would like to know how to link tmx lite with visual studio studio. It would also be useful to include an explanation for code::blocks for other users. :)

**Comment by fallahn** [comment]
Linking the library is no different to linking any other.

In project properties:
C/C++->General->Additional Include Directories, add the path to the tmxlite include folder

Linker->General->Additional Library Directories, add the path to the folder containing the tmxlite *.lib files

Linker->Input->Additional Dependencies, add the name of the library file to which to link eg libtmxlite-s.lib for static release or libtmxlite-s-d.lib for static debug

Presumably Code::Blocks is similar, but I've never used it.

**Comment by Bramwell-Simpson** [comment]
@fallahn you saved my life :)
