### ISSUE TITLE
Crash on object layer load

### ISSUE THREAD

**Issue by kraxarn** [fallahn/tmxlite#21]
Whenever I try to load any map, it crashes with the following error on `Map map; map.load("map.tmx");`:
`
Unhandled exception at 0x749B08B2 in tmx.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00739550. occurred
`
Map loads and renders fine in the older sfml-tmxloader library.
Running Visual Studio 2017 15.4.2 on Windows 10. Tried both using the pre-compiled binaries, compiled my own and included the source code directly, all crashes.

**Comment by fallahn** [comment]
Without running through a debugger myself I can't really say for sure. Can you share a map file which reproduces the problem so I can take a look?

**Comment by kraxarn** [comment]
[Here](https://dropfile.to/QTstLBE)'s the map I used for testing. Of course, then it would be `map.load("0-1tmx");` instead.

**Comment by fallahn** [comment]
![parse_test](https://user-images.githubusercontent.com/5619252/32567711-033c9fb4-c4b4-11e7-8726-0894ddc64e1e.png)
I've just run the map through the parse test program and it loads OK. Are you possibly mixing debug/release builds perhaps? And are you doing anything else to the map file or does it crash before map.load() can even return true or false? I'm running the same setup as you except on Windows 7

**Comment by kraxarn** [comment]
I've tried both debug and release builds with respective libraries and both fail with that error. `map.load` doesn't have time to return a value before it crashes. As I also tried including the source files directly, I doubt it's that. Although, now that I include the source files directly, I now get [this runtime error](https://vgy.me/e5aNUW.png) instead.

**Comment by fallahn** [comment]
Ah. Looking at the previous [out of range](http://en.cppreference.com/w/cpp/error/out_of_range) exception, I'm beginning to to think this may be to do with the way strings are handled with different locale settings / whether the underlying string uses widechars or not - I've come across something similar in the logger class. I'm going to need to have a think about how to reproduce the bug my end. As a wild stab it might happen around [here](https://github.com/fallahn/tmxlite/blob/master/tmxlite/src/Object.cpp#L104) - you could try commenting parts out to see if it makes a difference. This is most vexing, indeed.

**Comment by Cthutu** [comment]
This occurs because the code assumes you have a path before the .tmx file name - if you don't have a path separator ('/' or '\') the code attempt to pop_back on an empty string.
