### ISSUE TITLE
Maps are being displayed incorrectly

### ISSUE THREAD

**Issue by JonahHenriksson** [fallahn/tmxlite#23]
<img width="538" alt="problem" src="https://user-images.githubusercontent.com/33059163/32748030-d703e0c8-c888-11e7-829b-591e4c0b77fb.PNG">
This is a problem, and I don't know if I am doing something wrong. I am using sfml with that sfml orthographic header and I get stuff like this. With bigger maps, only parts are shown. Could you please tell me how to avoid stuff like this and what I need to change to prevent it from happening again. The picture is showing just a small area of the screen. The map is being displayed and then the map is being displayed again next to it, just up a tile. Bigger maps, as I said, are being partly shown. It is like there is a border that I can't stop, that keeps on messing up things. Some help would be appreciated. It looks like it also happens with the sfml examples as well. I am using VS 2017 and sfml 2.4. If you need anything, I would gladly send it. Thanks so much.

**Comment by fallahn** [comment]
I think this is related to #14 The chunk sizes are being incorrectly calculated. You'll have to look at [create chunks](https://github.com/fallahn/tmxlite/blob/master/SFMLExample/src/SFMLOrthogonalLayer.hpp#L217) or [update visibility](https://github.com/fallahn/tmxlite/blob/master/SFMLExample/src/SFMLOrthogonalLayer.hpp#L279) to try and hunt down the bug

**Comment by JonahHenriksson** [comment]
Now that I messed around with it. I think that this border that I am looking at is the result of the current window size you set it to in fullscreen mode in sfml. I will try to look at it more.

**Comment by JonahHenriksson** [comment]
Yeah, it had to do with being in fullscreen for me.
