### ISSUE TITLE
Installs to wrong folder for 64bit Linux

### ISSUE THREAD

**Issue by cdr255** [fallahn/tmxlite#35]
## Issue

Using the 1.0.1 release tarball and cmake, the library installs to the /usr/lib directory regardless of its architecture. 

## Explanation

On most *nix distributions, 'lib' is for 32 bit libraries and 'lib64' is for 64 bit libraries. This allows the 32 bit library to be installed alongside the 64 bit library, for compatibility.

It seems the `tmxlite/CMakeLists.txt` file explicitly defines this when installing as a shared library. If there's no specific need for this, it would be easier to package and use this library if it would allow CMake to use the system defaults for folder locations. It will also make the project more portable, in case someone wants to compile on a non-FHS *nix system.

## Suggestion

If You `include(GNUInstallDirs)`, You can use the already-populated variables `${CMAKE_INSTALL_INCLUDEDIR}`, `${CMAKE_INSTALL_LIBDIR}`, and `${CMAKE_INSTALL_BINDIR}` in place of the presently hard coded `include`, `lib`, and `bin`.

**Comment by fallahn** [comment]
Hi, thanks for the feedback! Installing to /usr/lib was indeed a mistake (it was intended to be /usr/local/lib). I've updated the CMake file with your suggestion and 64 bit binaries are now installed in lib64
