### ISSUE TITLE
Bug in colourFromString

### ISSUE THREAD

**Issue by pedro-w** [fallahn/tmxlite#4]
I am getting 'not a valid colour string' errors when loading a map. Tiled is saving the background colour like this '#ffffff' and the line [here](https://github.com/fallahn/tmxlite/blob/master/tmxlite/include/tmxlite/FreeFuncs.hpp#L138) converts it to 'fffffff' i.e. a seven character string.

One solution is to write that line as 
````
str.erase (std::remove(str.begin(), str.end(), '#'), str.end());
````
(as discussed [here](https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom))

I am using MacOS. It may be that other versions of the C++ library do not cause this issue but I don't think that can be relied on according to the standard.

**Comment by fallahn** [comment]
Would have used your fix as it is neater, but I already had this sitting here, had just forgotten to commit!
