### ISSUE TITLE
Getting two compile errors: `error C2610` upon building project

### ISSUE THREAD

**Issue by MrHallows** [fallahn/tmxlite#41]
I'm getting the following errors upon building my project in Visual Studio:
```
..\include\tmxlite\map.hpp(98): error C2610: 'tmx::Map::Map(tmx::Map &&)' : is not a special member function which can be defaulted
..\include\tmxlite\map.hpp(99): error C2610: 'tmx::Map &tmx::Map::operator =(tmx::Map &&)' : is not a special member function which can be defaulted
```

Here are lines 98 and 99 of `Map.hpp`, respectively:
```
Map(Map&&) = default;
Map& operator = (Map&&) = default;
```

Are you able to provide some insight into why I'm getting these errors? Thank you!

**Comment by fallahn** [comment]
The root cause of the problem is that the `Map` class contains members which are non-copyable, specifically instances of `unique_ptr`. However as these themselves should be default movable, default move construction and assignment should work fine. A quick google suggests that older versions of Visual Studio do not support defaulted move construction/assignment (see [here](https://stackoverflow.com/questions/24573963/move-constructor-invalid-type-for-defaulted-constructor-vs-2013)) - which version of Visual Studio are you using?

**Comment by MrHallows** [comment]
Okay, interesting. I'm using Visual Studio 2013, unfortunately. I have the 2015 and 2017 editions, but they are not activated, as I cannot afford to purchase a license key.

**Comment by MrHallows** [comment]
I've got Visual Studio 2017 up and running, but now I'm getting the following linker errors:

```
1>   Creating library ..\OpalEngine2D\Debug\OpalEngine2D.lib and object ..\OpalEngine2D\Debug\OpalEngine2D.exp
1>Map.obj : error LNK2019: unresolved external symbol "public: __thiscall tmx::Property::Property(void)" (??0Property@tmx@@QAE@XZ) referenced in function "public: void __thiscall std::allocator<class tmx::Property>::construct<class tmx::Property>(class tmx::Property *)" (??$construct@VProperty@tmx@@$$V@?$allocator@VProperty@tmx@@@std@@QAEXPAVProperty@tmx@@@Z)
1>Map.obj : error LNK2019: unresolved external symbol "public: void __thiscall tmx::Property::parse(class pugi::xml_node const &)" (?parse@Property@tmx@@QAEXABVxml_node@pugi@@@Z) referenced in function "protected: void __thiscall tmx::Layer::addProperty(class pugi::xml_node const &)" (?addProperty@Layer@tmx@@IAEXABVxml_node@pugi@@@Z)
1>Map.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall tmx::ObjectGroup::parse(class pugi::xml_node const &)" (?parse@ObjectGroup@tmx@@UAEXABVxml_node@pugi@@@Z)
1>Map.obj : error LNK2019: unresolved external symbol "public: __thiscall tmx::Map::Map(void)" (??0Map@tmx@@QAE@XZ) referenced in function "public: void __thiscall CMap::LoadMap(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadMap@CMap@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>Map.obj : error LNK2019: unresolved external symbol "public: bool __thiscall tmx::Map::load(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?load@Map@tmx@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: void __thiscall CMap::LoadMap(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadMap@CMap@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>Map.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall tmx::TileLayer::parse(class pugi::xml_node const &)" (?parse@TileLayer@tmx@@UAEXABVxml_node@pugi@@@Z)
1>..\OpalEngine2D\Debug\OpalEngine2D.exe : fatal error LNK1120: 6 unresolved externals
1>Done building project "OpalEngine2D.vcxproj" -- FAILED.
```

**Comment by fallahn** [comment]
It could be a linker configuration error. I usually build the static version of tmxlite and make sure to link tmxlite-s-d.lib in debug mode and tmxlite-s.lib in release builds. The compiler versions also have to match - so if you built tmxlite with VS2017 you'll also need to move your project to that too (it's a pain, I know, but can't be helped unfortunately)

**Comment by MrHallows** [comment]
Good to know. And no worries; I've actually moved my project to VS2017 already, so the rest shouldn't be too bad. I'll give that a whirl and let you know if it works out. I appreciate all of your help thus far.

**Comment by MrHallows** [comment]
Okay, so I've built both static versions of the debug and release builds, which created `libtmxlite-s-d.lib` and `libtmxlite-s.lib`, respectively. And it is officially running again.  I apologise in advance for the potentially stupid questions, but I've currently got my configuration set to `All Configurations` and I've included the `libtmxlite-s-d.lib` file (for obvious reasons). My questions are:

1) When the time comes to build a release version, `libtmxlite-s-d.lib` will simply need to be swapped out with `libtmxlite-s.lib` in the linker configuration, correct?
2) When static libraries are used, only the associated header files need to be in the project directory, correct? That is, not the source files. (I have not had much experience using static libraries at this point.)

**Comment by fallahn** [comment]
1. That is correct :) The difference between the debug and release versions is that they, in turn, link to different versions of Microsoft's C runtime - so this has to match up with your project when it's compiled.

2. Also correct. The source files for tmxlite are now already compiled and contained within the .lib file. The headers are required so your project knows what's contained within the lib. The linker will then pull out and link the pieces required from the library to your executable when it is compiled.

Happy to help!

**Comment by MrHallows** [comment]
Oh, okay. I'll keep that in mind for the day I can finally finish this project. ;)

Awesome! I was hoping to "trim the fat" where I can, so this ended up being beneficial in more ways than one. Needless to say, I'm working on a 2D engine and platformer game, so once I get my bearings on separating the two into different projects, it would be nice to build the engine as a static library for use with future projects. :)

Matt, thank you so much for all of your help and for writing/providing such a helpful tool. I truly appreciate it.

**Comment by fallahn** [comment]
You're very welcome! For reference when creating your own library you might check out my other project [xygine](https://github.com/fallahn/xygine) - it started in exactly the same way and has been a labour of love for many years now :D
