### ISSUE TITLE
SFML collision detection

### ISSUE THREAD

**Issue by NathanHoekstra** [fallahn/tmxlite#44]
I am trying to detect the collision with a movable player and an Tiled "Intersectable" layer. I tried following this guide https://trederia.blogspot.com/2013/10/collision-detection-with-tiled-maps.html but it seems to not work anymore. I know that this was written for sfml-tmxloader but the Github repo states that tmxlite also has support for SFML. I can't find how to do this with tmxlite.

**Comment by fallahn** [comment]
tmxlite differs from sfml-tmxloader in that it only parses the data stored in a tmx map file into a set of C++ objects. It doesn't support rendering with sfml directly like sfml-tmxloader does, although there is an example in the repository of how to render maps loaded by tmxlite with sfml.

To do collision detection I would do something like this:
- Create a 'collision' or 'intersectable' layer in Tiled which is an object group type. Place down objects on this layer which represent the collision zones. You can use different shapes for your objects, but to start simple I recommend just using rectangles to create AABBs
- Load the map with tmxlite and grab the layers vector from the `Map` object using `getLayers()`. Find your collision layer, and then get all the objects from that layer (see [this](https://github.com/fallahn/tmxlite/blob/master/ParseTest/src/main.cpp#L53) example for how to do that).
- Then for each object use `getAABB()` and convert it to `sf::FloatRect` and store it somewhere, for an example `std::vector<sf::FloatRect>` which will become your list of collision objects.

Once you have all your collision data loaded you can use it with a physics library like box2D or start creating your own collision. I've written an sfml tutorial [here](https://trederia.blogspot.com/2016/02/2d-physics-101-pong.html) which also has links to other tutorials at the bottom. HTH!

**Comment by NathanHoekstra** [comment]
Hi, thanks for the quick response!

`
std::vector<sf::FloatRect> bounds;`
`
const auto& layer = map.getLayers()[2];
const auto& objects = layer->getLayerAs<tmx::ObjectGroup>().getObjects();`
`
for (const auto& object : objects) {`
     `tmx::FloatRect rect = object.getAABB();`
     `bounds.push_back(sf::FloatRect(rect.left, rect.top, rect.width, rect.height));`
`}
`
But on runtime i get the following assertion error:
`Expression: getType() == Type::Object
AL lib: (EE) alc_cleanup: 1 device not closed`
It gives this error on line 88 in the ObjectGroup.hpp file

**Comment by fallahn** [comment]
I think the AL lib part is a separate error and should appear on its own line (it's to do with the program aborting). The actual error is the assertion failing - it checks to see if `getType()` is returning an object type layer, because that's what you're requesting, but it seems the layer you want is not the correct type.

You can do something like this:

    for(const auto& layer : layers)
    {
        if(layer->getType() == tmx::Layer::Type::Object)
        {
            //this is the layer you want, try getLayerAs() here.
        }
    }

or if you want to use some STL magic:

    auto result = std::find_if(layers.begin(), layers.end(),[](const tmx::Layer& l){return l->getType() == tmx::Layer::Type::Object;});
    if(result != layers.end())
    {
        const auto& objectLayer = result->getLayerAs<tmx::ObjectGroup>();
    }
    else
    {
        std::cout << "Object layer not found\n";
    }

**Comment by MarcDirven** [comment]
Hi Fallahn, NathanHoekstra is my collegue. It turned out we designed our map faulty. We designed the map with tiles only, while your library only can intersect with objects, which makes sence. Thanks alot for your help!
