### ISSUE TITLE
Features missing for TMX 1.0 support?

### ISSUE THREAD

**Issue by Grant1219** [fallahn/tmxlite#52]
From a brief look through the code it appears that tmxlite supports the `<text>` element within objects, and the `tile.type` for tilesets.

The would mean the only feature keeping tmxlite from supporting TMX 1.0 is the `<group>` tag for nesting layers?
https://doc.mapeditor.org/en/stable/reference/tmx-changelog/#tiled-1-0

I am considering adding support for the `<group>` tag, but I wanted to make sure it wasn't already a work in progress. :smiley:

**Comment by fallahn** [comment]
Hi! Yes, I think you're right. `<group>` tags are not currently being worked on, if you'd like to contribute support for them, I'd be very grateful :) Thanks

**Comment by Grant1219** [comment]
PR related to this question here: https://github.com/fallahn/tmxlite/pull/53
