### ISSUE TITLE
Expose size of the tileset image

### ISSUE THREAD

**Issue by u3shit** [fallahn/tmxlite#61]
According to the [TMX spec](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/) `<image>` can contain `width` and `height` with the size of the referenced image (it's optional, but it looks like tiled writes it). Right now tmxlite ignores these attributes, and the only way to figure out the size of the image is to actually load it (completely unnecessary in some cases).
I've hacked in the support for this in my local checkout, I can turn it into a proper PR if that helps.

**Comment by fallahn** [comment]
Ah, I assume this is when parsing tile sets? If so this is indeed an oversight (image layers do parse the [size attributes](https://github.com/fallahn/tmxlite/blob/master/tmxlite/src/ImageLayer.cpp#L69)). If you want to submit a PR that would be fantastic, else I can add it when I get some time. Thanks!
