### ISSUE TITLE
I get the following error when loading the map (which contains GroupLayer). Any help is greatly appreciated!

### ISSUE THREAD

**Issue by RitwickVerma** [fallahn/tmxlite#67]
As stated, I get the error when I load the map saying
`ObjectGroup.cpp:45: virtual void tmx::ObjectGroup::parse(const pugi::xml_node&, tmx::Map*): Assertion 'map' failed.`

Here is the structure of my layers:
![Screenshot_tmx_error1](https://user-images.githubusercontent.com/16993844/83128492-5df08500-a090-11ea-9f1f-7b7e35ff4808.png)

I get different error when I  remove object layers from the group
![Screenshot_tmx_error](https://user-images.githubusercontent.com/16993844/83127583-32b96600-a08f-11ea-808f-97d71cf48db8.png)
(First make exec error is when I delete the object layers from the groups (the ones called "thing"). Second error is the one I get If I keep all the object layers in their respective groups)

Also, I get no errors if I remove the groups altogether. Which makes me believe there is some peoblem in importing groups

**Comment by fallahn** [comment]
Hi! This is indeed a bug. I've pushed a potential fix to master, if you'd like to try it out. Thanks!

**Comment by RitwickVerma** [comment]
Wow didn't expect such a quick response!

So I tried it out again and theres what I get 
![Screenshot_tmx_error2](https://user-images.githubusercontent.com/16993844/83140715-5d151e80-a0a3-11ea-815b-c53a1306b9b7.png)

None of the layers in the groups are parsed. The outer object layers ("spawn_points" and "collision") are parsed perfectly though.

**Comment by fallahn** [comment]
No problem! It irks me when I don't have things right ;) I've pushed another commit, hopefully this one will nail it.

**Comment by RitwickVerma** [comment]
Awesome! Everything works perfectly now. Thanks a lot :)
