### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by thechubbypanda** [fallahn/tmxlite#84]
This looks to be a very useful library. I'm looking to use it for a university project, so I need proof of legality of use. How come there's no license associated with the project when it seems it's built for others to use?

**Comment by thechubbypanda** [comment]
Just realized that I was searching the wrong spelling of license. I see that the files are under BSD, might be nice to have a separate license file anyway?

**Comment by fallahn** [comment]
Hi! The source is actually licensed under the zlib license. I've added a license file to help clarify, thanks for the feedback.
