### ISSUE TITLE
what are the steps on building TMXLite libraries

### ISSUE THREAD

**Issue by WilliamWangPeng** [fallahn/tmxlite#85]
Hi dear author  
    I want to build TMXLite libraries on ubuntu 16.04, but I don't know the steps,  

thank you
Best Regards
William

**Comment by fallahn** [comment]
Hi
Make sure you have installed g++, git and cmake via apt.

Clone this repository to somewhere:

    mkdir ~/repositories && cd ~/repositories
    git clone https://github.com/fallahn/tmxlite.git

Then use cmake to build/install the library

    cd tmxlite/tmxlite && mkdir build && cd build
    cmake ..
    sudo make install

More info can be found on the quickstart guide: https://github.com/fallahn/tmxlite/wiki/Quick-Start

**Comment by WilliamWangPeng** [comment]
> Hi
> Make sure you have installed g++, git and cmake via apt.
> 
> Clone this repository to somewhere:
> 
> ```
> mkdir ~/repositories && cd ~/repositories
> git clone https://github.com/fallahn/tmxlite.git
> ```
> 
> Then use cmake to build/install the library
> 
> ```
> cd tmxlite/tmxlite && mkdir build && cd build
> cmake ..
> sudo make install
> ```
> 
> More info can be found on the quickstart guide: https://github.com/fallahn/tmxlite/wiki/Quick-Start

hi dear fallahn  
    I did the steps as you said, nowadays when I install https://github.com/connorkuehl/sdl2-tiled-example, 
![image](https://user-images.githubusercontent.com/51076736/111635428-6dfd6f00-8832-11eb-80e2-30a3dd2ecd04.png)
  


the errors are:    
![image](https://user-images.githubusercontent.com/51076736/111635514-866d8980-8832-11eb-8245-1f012e6b709d.png)
  

I don't know why? 

thank you
Best Regards
William

**Comment by fallahn** [comment]
This looks to be a problem with the cmake configuration in the sdl2 example. Try copying the updated FindTMXLITE.cmake file from the tmxlite/cmake/modules directory to the sdl2-tiled-example/cmake directory.

**Comment by WilliamWangPeng** [comment]
> This looks to be a problem with the cmake configuration in the sdl2 example. Try copying the updated FindTMXLITE.cmake file from the tmxlite/cmake/modules directory to the sdl2-tiled-example/cmake directory.


thank you dear  
    I have another question which is how to set "cmake multi-thread disabled" in cmake building？  

thank you  
Best Regards  
Wiiliam

**Comment by WilliamWangPeng** [comment]
> This looks to be a problem with the cmake configuration in the sdl2 example. Try copying the updated FindTMXLITE.cmake file from the tmxlite/cmake/modules directory to the sdl2-tiled-example/cmake directory.


thank you dear expert  
    I have followed your advice which still reports the problem,    

![image](https://user-images.githubusercontent.com/51076736/111803768-54c7f180-890a-11eb-8a24-a2765fe4af0f.png)  

![image](https://user-images.githubusercontent.com/51076736/111803872-76c17400-890a-11eb-9a7f-4c5c38c1e6ef.png)
  
maybe it is the problem of sdl2-example， I have reported to them but no reply until now  
https://github.com/connorkuehl/sdl2-tiled-example/issues/2#issue-834828219  

thank you for your kindness :)  
by the way, do you know how to disable multi-thread when using cmake?  

thank you again  
best regards  
William

**Comment by fallahn** [comment]
This looks like a mis-configuration of CMAKE_MODULE_PATH in the cmake file provided with the sdl2 example. Check that this is set to the correct directory.

Alternatively try the OpenGL example included with TMXLite as this also uses SDL2.

I don't know what the multi-thread option is. If it is a cmake option then you will need to check the cmake documentation.

**Comment by WilliamWangPeng** [comment]
> This looks like a mis-configuration of CMAKE_MODULE_PATH in the cmake file provided with the sdl2 example. Check that this is set to the correct directory.  

hi dear  fallahn @fallahn    
    The CMAKE_MODULE_PATH in the sdl2 example is here, how can we correct? I have included the tmxlite-master in the main directory of the sdl2 example.  
![image](https://user-images.githubusercontent.com/51076736/111815691-f05f5f00-8916-11eb-80e3-2e1ecdfccc52.png)
  
![image](https://user-images.githubusercontent.com/51076736/111816010-492ef780-8917-11eb-8419-c98e7d668148.png)
  

> 
> Alternatively try the OpenGL example included with TMXLite as this also uses SDL2.    
Could you give me the linking of OpenGL example? the reason why I use sdl2 example is that sdl2 example uses rendering method.  
> 
> I don't know what the multi-thread option is. If it is a cmake option then you will need to check the cmake documentation.  

I found just now, which was defined in CMakeLists.txt using CMAKE_FLAGS(  -pthread )  

thank you for your kindness  
Best Regards  
William

**Comment by antonialoytorrens** [comment]
I have also run into the same issue.

Seems that the original author of https://github.com/connorkuehl/sdl2-tiled-example did a Rename of cmake_modules folder, but forgot about updating it in `CMakeLists.txt`.

As the repository is now read-only, here's the needed patch that builds the repository successfully.

[fix-build.patch.zip](https://github.com/fallahn/tmxlite/files/9893947/fix-build.patch.zip)
