### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by jonpchin** [fallahn/tmxlite#89]
Can this library be built for iOS?

**Comment by fallahn** [comment]
It uses standard C++ so there's no reason why it shouldn't work, but I don't have the hardware to test it on.

The only potential caveat is that on Android fstream is not implemented, so you need to load the map file into a string first, and then load it with `Map::loadFromString()` . However, like I say, I've not tested on iOS so I don't know if this holds true for all mobile platforms. Perhaps someone with experience can give a better answer.
