### ISSUE TITLE
tmx::TileSet::HasTransparency()

### ISSUE THREAD

**Issue by Deedolith** [fallahn/tmxlite#98]
Hello,

I found out that tmx::TileSet::HasTransparency() return true even if the tilset has no transparency.

Tested on Visual studio 2019 (V 16.6.9) under Windows10.
TmxLite (2019-03-05) installed with vcpkg.

Side notes:
Can you keep repositories for packages managers (vcpkg, NuGet, yum, dnf ect ....) up to date ?
packages on vcpkg are out of date, and packages on NuGet are beyond out of date (no clue about linux package managers).

**Comment by fallahn** [comment]
Hi, thanks for finding this, it should be fixed now.

Unfortunately I have no control over the package managers - in fact I had no idea tmxlite appeared in any of them! However, if you are using cmake, you can use your  cmake script to clone and build the latest version of tmxlite (or any specific version)

    find_package(TMXLITE QUIET)

    if (NOT ${TMXLITE_FOUND})
      message(STATUS "tmxlite not found, fetching from github...")
      include(FetchContent)
      FetchContent_Declare(
        tmxlite
        GIT_REPOSITORY https://github.com/fallahn/tmxlite
        GIT_TAG        1.2.2
      )
      FetchContent_MakeAvailable(tmxlite)
      add_subdirectory(${tmxlite_SOURCE_DIR}/tmxlite)
      set(TMXLITE_LIBRARIES tmxlite)
      set(TMXLITE_INCLUDE_DIR ${tmxlite_SOURCE_DIR}/tmxlite/include)
    endif()

You can set `GIT_TAG` to any tagged version, commit hash or simply `origin/master` to get the latest revision. Hope this helps!
